# Generated by Django 5.0.3 on 2024-05-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.CharField(default='...', max_length=200),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='author/149071.png', upload_to='author/'),
        ),
    ]
